import React, { useRef } from 'react';
import { 
  FileText, 
  Download, 
  Printer, 
  X, 
  CheckCircle2, 
  AlertTriangle, 
  TrendingUp, 
  Sparkles, 
  ShieldCheck, 
  Calendar,
  DollarSign,
  PieChart
} from 'lucide-react';
import { CATEGORIES } from '../data/initialData';
import { analyzeCategoryBudgets } from '../services/aiAdvisorEngine';
import { playSound, triggerConfetti } from '../utils/effects';

export default function MonthlyReportModal({ 
  isOpen, 
  onClose, 
  scenario, 
  income, 
  expenses = [], 
  budgets = {}, 
  savingsGoals = [], 
  health, 
  currency = '$',
  soundEffects = true
}) {
  const reportRef = useRef(null);

  if (!isOpen) return null;

  const totalIncome = typeof income === 'number' ? income : (income || []).reduce((s, i) => s + (Number(i.amount) || 0), 0);
  const totalExpense = expenses.reduce((s, e) => s + (Number(e.amount) || 0), 0);
  const netSavings = totalIncome - totalExpense;
  const savingsRate = totalIncome > 0 ? (netSavings / totalIncome) * 100 : 0;
  const analysis = analyzeCategoryBudgets(expenses, budgets);

  const currentDate = new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });

  const handlePrint = () => {
    if (soundEffects) playSound('click');
    window.print();
  };

  const handleDownload = () => {
    if (soundEffects) {
      playSound('success');
      triggerConfetti('medium');
    }
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-black/80 backdrop-blur-md overflow-y-auto animate-fade-in">
      <div className="bg-[#0f172a] border border-white/15 rounded-3xl w-full max-w-4xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden my-auto">
        
        {/* Top Control Bar */}
        <div className="p-4 sm:px-6 bg-[#1e293b]/90 border-b border-white/10 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-bold text-white text-base">Monthly Financial Intelligence Statement</h3>
              <p className="text-xs text-slate-400">Reporting Period: {currentDate} &bull; Generated by FinAI</p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 border border-white/10 text-xs font-semibold text-slate-200 transition-colors"
            >
              <Printer className="w-3.5 h-3.5 text-emerald-400" />
              <span className="hidden sm:inline">Print</span>
            </button>

            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-xl bg-gradient-to-r from-emerald-600 to-teal-500 hover:from-emerald-500 hover:to-teal-400 text-white text-xs font-bold shadow-neon-emerald transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export PDF</span>
            </button>

            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-white rounded-xl bg-slate-800/80 hover:bg-slate-700 transition-colors"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Printable Report Document Body */}
        <div ref={reportRef} className="flex-1 overflow-y-auto p-6 sm:p-8 space-y-6 text-slate-200 bg-[#0a0f1d] print:bg-white print:text-black">
          
          {/* Header Banner */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center pb-6 border-b border-white/10 gap-4">
            <div>
              <div className="flex items-center gap-2">
                <span className="text-2xl font-black tracking-tight text-white print:text-black">
                  Fin<span className="text-emerald-400">AI</span> Monthly Executive Audit
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-1">
                Account Holder: <strong className="text-white print:text-black">{scenario?.persona}</strong> ({scenario?.name} &bull; {scenario?.role})
              </p>
            </div>

            <div className="text-left sm:text-right">
              <span className={`text-xs font-extrabold uppercase px-3 py-1 rounded-full border ${health?.badgeColor || 'text-emerald-400 bg-emerald-500/10'}`}>
                Health Score: {health?.score}/100 ({health?.grade})
              </span>
              <div className="text-[11px] text-slate-400 mt-1">Runway: {health?.runwayMonths} Months of Reserve</div>
            </div>
          </div>

          {/* AI Executive Summary Callout */}
          <div className="p-5 rounded-2xl bg-gradient-to-r from-emerald-950/40 via-teal-950/30 to-slate-900 border border-emerald-500/30 print:border-gray-300">
            <div className="flex items-center gap-2 text-emerald-400 font-bold text-sm mb-2">
              <Sparkles className="w-4 h-4" />
              <span>AI Strategic Executive Summary</span>
            </div>
            <p className="text-xs sm:text-sm text-slate-200 leading-relaxed print:text-gray-800">
              During the period of {currentDate}, your total gross income reached <strong>{currency}{totalIncome.toLocaleString()}</strong> across {Array.isArray(income) ? income.length : 1} revenue stream(s), with total operational expenditures of <strong>{currency}{totalExpense.toLocaleString()}</strong> ({((totalExpense/totalIncome)*100).toFixed(1)}% burn rate). You achieved a net savings surplus of <strong>{currency}{netSavings.toLocaleString()}</strong> ({savingsRate.toFixed(1)}% savings rate).
            </p>
          </div>

          {/* Key Cashflow Summary Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-slate-900/80 p-4 rounded-xl border border-white/10">
              <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Total Income Inflows</div>
              <div className="text-2xl font-black text-emerald-400 mt-1">+{currency}{totalIncome.toLocaleString()}</div>
              <div className="text-[10px] text-slate-500 mt-1">100% of cash revenue</div>
            </div>

            <div className="bg-slate-900/80 p-4 rounded-xl border border-white/10">
              <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Total Outflow Expenses</div>
              <div className="text-2xl font-black text-rose-400 mt-1">-{currency}{totalExpense.toLocaleString()}</div>
              <div className="text-[10px] text-slate-500 mt-1">{((totalExpense/totalIncome)*100).toFixed(0)}% of income</div>
            </div>

            <div className="bg-slate-900/80 p-4 rounded-xl border border-white/10">
              <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Net Surplus / Savings</div>
              <div className="text-2xl font-black text-blue-400 mt-1">{currency}{netSavings.toLocaleString()}</div>
              <div className="text-[10px] text-emerald-400 font-semibold mt-1">{savingsRate.toFixed(1)}% Savings Rate</div>
            </div>
          </div>

          {/* Category Budget Performance Table */}
          <div>
            <h4 className="text-sm font-bold text-white mb-3 flex items-center gap-2">
              <PieChart className="w-4 h-4 text-emerald-400" />
              Category Budget Adherence Audit
            </h4>
            <div className="overflow-x-auto rounded-xl border border-white/10">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-950 text-slate-400 uppercase font-semibold text-[10px] tracking-wider border-b border-white/10">
                  <tr>
                    <th className="py-2.5 px-3">Category</th>
                    <th className="py-2.5 px-3">Type</th>
                    <th className="py-2.5 px-3">Spent</th>
                    <th className="py-2.5 px-3">Budget Limit</th>
                    <th className="py-2.5 px-3">Utilization</th>
                    <th className="py-2.5 px-3 text-right">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/5 bg-slate-900/50">
                  {analysis.allCategories.filter(c => c.spent > 0 || c.budget > 0).map(cat => {
                    const isOver = cat.status === 'over';
                    return (
                      <tr key={cat.id}>
                        <td className="py-2.5 px-3 font-semibold text-white flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full" style={{ backgroundColor: cat.color }} />
                          {cat.name}
                        </td>
                        <td className="py-2.5 px-3 text-slate-400 capitalize">{cat.type}</td>
                        <td className="py-2.5 px-3 font-bold text-white">{currency}{cat.spent}</td>
                        <td className="py-2.5 px-3 text-slate-400">{currency}{cat.budget}</td>
                        <td className="py-2.5 px-3">
                          <div className="flex items-center gap-2">
                            <div className="w-16 bg-slate-800 rounded-full h-1.5 overflow-hidden">
                              <div 
                                className={`h-1.5 rounded-full ${isOver ? 'bg-rose-500' : 'bg-emerald-400'}`} 
                                style={{ width: `${Math.min(100, cat.percentage)}%` }}
                              />
                            </div>
                            <span className="text-[11px] text-slate-400">{cat.percentage}%</span>
                          </div>
                        </td>
                        <td className="py-2.5 px-3 text-right">
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md ${
                            isOver ? 'bg-rose-500/20 text-rose-300' : 'bg-emerald-500/20 text-emerald-300'
                          }`}>
                            {isOver ? `Over by ${currency}${Math.abs(cat.diff)}` : 'Compliant'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Actionable Next-Month Directives */}
          <div className="p-5 rounded-2xl bg-slate-900 border border-white/10">
            <h4 className="text-sm font-bold text-white mb-2 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              Actionable Directives for Next Month
            </h4>
            <div className="space-y-2 text-xs text-slate-300">
              {scenario?.aiRecommendations?.map((rec, idx) => (
                <div key={idx} className="flex items-start gap-2">
                  <span className="w-5 h-5 rounded-full bg-emerald-500/20 text-emerald-300 flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <p>{rec}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Verification Signature Seal */}
          <div className="pt-4 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between text-slate-500 text-[11px] gap-2">
            <span>Verified by FinAI Automated Intelligence Engine &bull; Version 2.4</span>
            <span>Security Hash: #{Math.random().toString(36).substring(2, 10).toUpperCase()} &bull; Timestamp: {new Date().toISOString()}</span>
          </div>

        </div>

      </div>
    </div>
  );
}
